version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    volumes:
      - .:/app
    ports:
      - "5010:5010"
    links:
      - proxy_redis
  proxy_redis:
    image: "redis"
    container_name: proxy_redis